services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: doc-analyzer-api
    env_file:
      - ./api/.env
    ports:
      - "3001:3000"

  cli:
    build:
      context: ./cli
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3001
    container_name: doc-analyzer-cli
    env_file:
      - ./cli/.env
    environment:
      - API_URL=http://doc-analyzer-api:3000
      - HOSTNAME=0.0.0.0
    ports:
      - "3000:3000"
