services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: doc-analyzer-api
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSL: "true"
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "3000:3000"

  cli:
    build:
      context: ./cli
      dockerfile: Dockerfile
    container_name: doc-analyzer-cli
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
    ports:
      - "3001:3000"
